name: pomodoro_knight
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flame: ^1.34.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  google_fonts: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/slime1/
    - assets/bat/
    - assets/player/
    - assets/background/
